dataset:
  path: D:\My projects\autorec\movielens-1m\
  sep: ;

datamodule:
  batch_size: 128

model:
  d: 3953 # 
  k: 500
  weight_decay: 100
  optimizer:
    lr: 0.001
    betas: [0.9, 0.98]
    eps: 1e-08
    weight_decay: 0.00001
  scheduler:
    step_size: 50
    gamma: 0.1
    verbose: True

logger:
  save_dir: logger
  name: autorec_logger

trainer:
  max_epochs: 1000
  accelerator: auto
  detect_anomaly: True
  log_every_n_steps: 1
  
ckpt:
  have_ckpt: False
  ckpt_path: D:\My projects\autorec\logs\logger\autorec_logger\version_0\checkpoints\epoch=999-step=48000.ckpt\