dataset:
  path: D:\My projects\autorec\movielens-1m\
  sep: ;

datamodule:
  batch_size: 32

model:
  d: 3953 # 
  k: 500
  weight_decay: 100
  min_rating: 1
  max_rating: 5
  optimizer:
    lr: 0.0001
    betas: [0.9, 0.98]
    eps: 1e-06
    weight_decay: 0.0001

logger:
  save_dir: logger
  name: autorec_logger

trainer:
  max_epochs: 2000
  accelerator: auto
  detect_anomaly: True
  log_every_n_steps: 1