dataset:
  path: D:\My projects\autorec\movielens-1m\
  sep: ;

datamodule:
  batch_size: 128

model:
  d: 3953 # 
  k: 1028
  weight_decay: 100
  optimizer:
    lr: 0.001
    betas: [0.9, 0.98]
    eps: 1e-06
    weight_decay: 0.0001

logger:
  save_dir: logger
  name: autorec_logger

trainer:
  max_epochs: 100
  accelerator: auto
  detect_anomaly: True
  